title: XFP
# replace title by this later
# logo: assets/images/medium.webp
nav_external_links:
  - title: View on GitHub
    url: https://github.com/sebvey/python-fp

enable_copy_code_button: true

callouts:
  further-reading:
    title: a bit of reading
    color: green
  note:
    title: note
    color: blue
  warning:
    title: warning
    color: red
  for-short:
    title: for short
    color: green

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "9.1.3"

# Build settings
theme: just-the-docs
plugins:
 - jekyll-feed
